In [67]:
import pandas as pd
import numpy as np

In [68]:
train_df = pd.read_csv("train.csv") #verileri yükledim.
test_df = pd.read_csv("test.csv")

In [69]:
train_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [70]:
test_df

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
413,1305,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [71]:
train_df = train_df.drop(["Name","Ticket","Cabin"], axis=1) #gereksiz sütunları kaldırdım.
test_df = test_df.drop(["Name","Ticket","Cabin"], axis=1) #hem train hem test sütunu için de.

In [72]:
train_df

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
0,1,0,3,male,22.0,1,0,7.2500,S
1,2,1,1,female,38.0,1,0,71.2833,C
2,3,1,3,female,26.0,0,0,7.9250,S
3,4,1,1,female,35.0,1,0,53.1000,S
4,5,0,3,male,35.0,0,0,8.0500,S
...,...,...,...,...,...,...,...,...,...
886,887,0,2,male,27.0,0,0,13.0000,S
887,888,1,1,female,19.0,0,0,30.0000,S
888,889,0,3,female,NaN,1,2,23.4500,S
889,890,1,1,male,26.0,0,0,30.0000,C
890,891,0,3,male,32.0,0,0,7.7500,Q

In [73]:
test_df

     PassengerId  Pclass     Sex   Age  SibSp  Parch      Fare Embarked
0            892       3    male  34.5      0      0    7.8292        Q
1            893       3  female  47.0      1      0    7.0000        S
2            894       2    male  62.0      0      0    9.6875        Q
3            895       3    male  27.0      0      0    8.6625        S
4            896       3  female  22.0      1      1   12.2875        S
..           ...     ...     ...   ...    ...    ...       ...      ...
413         1305       3    male   NaN      0      0    8.0500        S
414         1306       1  female  39.0      0      0  108.9000        C
415         1307       3    male  38.5      0      0    7.2500        S
416         1308       3    male   NaN      0      0    8.0500        S
417         1309       3    male   NaN      1      1   22.3583        C

[418 rows x 8 columns]

In [74]:
from sklearn.impute import SimpleImputer #simleımputer ile eksik verileri doldurdum.
imputer_sayisal = SimpleImputer(missing_values=np.nan, strategy="mean") #sayısal veri için.
train_df[["Age","Fare"]] = imputer_sayisal.fit_transform(train_df[["Age","Fare"]])
test_df[["Age","Fare"]] = imputer_sayisal.transform(test_df[["Age","Fare"]])

imputer_kategorik = SimpleImputer(missing_values=np.nan, strategy="most_frequent") #kategorik veriler için en çok tekrar eden
train_df[["Embarked"]] = imputer_kategorik.fit_transform(train_df[["Embarked"]])
test_df[["Embarked"]] = imputer_kategorik.transform(test_df[["Embarked"]])

In [75]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
le = LabelEncoder()

train_df["Sex"] = le.fit_transform(train_df["Sex"]) #cinsiyetleri 0 1 e çevirdim
test_df["Sex"] = le.transform(test_df["Sex"])
train_df
test_df

     PassengerId  Pclass  Sex        Age  SibSp  Parch      Fare Embarked
0            892       3    1  34.500000      0      0    7.8292        Q
1            893       3    0  47.000000      1      0    7.0000        S
2            894       2    1  62.000000      0      0    9.6875        Q
3            895       3    1  27.000000      0      0    8.6625        S
4            896       3    0  22.000000      1      1   12.2875        S
..           ...     ...  ...        ...    ...    ...       ...      ...
413         1305       3    1  29.699118      0      0    8.0500        S
414         1306       1    0  39.000000      0      0  108.9000        C
415         1307       3    1  38.500000      0      0    7.2500        S
416         1308       3    1  29.699118      0      0    8.0500        S
417         1309       3    1  29.699118      1      1   22.3583        C

[418 rows x 8 columns]

In [76]:
#-------Train Verisi İçin İşlemler-----------
ohe = OneHotEncoder()
embarked_train = ohe.fit_transform(train_df[["Embarked"]]).toarray()
embarked_train_df = pd.DataFrame(embarked_train, columns=ohe.get_feature_names_out(['Embarked'])) #df yaptım , makinenin oluşturduğu isimsiz sütunlara otomatik isim etiketi yapıştırmasını sağlar. son kod.
embarked_train_df.index = train_df.index #hata almamak için önemli,indexleri düzelt
train_df = train_df.drop("Embarked", axis=1) #eski embarked sütunun atıp
train_df = pd.concat([train_df, embarked_train_df], axis=1) # yerine yeni oluştudugumuz sütunu ekledik.

embarked_train_df

     Embarked_C  Embarked_Q  Embarked_S
0           0.0         0.0         1.0
1           1.0         0.0         0.0
2           0.0         0.0         1.0
3           0.0         0.0         1.0
4           0.0         0.0         1.0
..          ...         ...         ...
886         0.0         0.0         1.0
887         0.0         0.0         1.0
888         0.0         0.0         1.0
889         1.0         0.0         0.0
890         0.0         1.0         0.0

[891 rows x 3 columns]

In [77]:
train_df

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked_C,Embarked_Q,Embarked_S
0,1,0,3,1,22.000000,1,0,7.2500,0.0,0.0,1.0
1,2,1,1,0,38.000000,1,0,71.2833,1.0,0.0,0.0
2,3,1,3,0,26.000000,0,0,7.9250,0.0,0.0,1.0
3,4,1,1,0,35.000000,1,0,53.1000,0.0,0.0,1.0
4,5,0,3,1,35.000000,0,0,8.0500,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,1,27.000000,0,0,13.0000,0.0,0.0,1.0
887,888,1,1,0,19.000000,0,0,30.0000,0.0,0.0,1.0
888,889,0,3,0,29.699118,1,2,23.4500,0.0,0.0,1.0
889,890,1,1,1,26.000000,0,0,30.0000,1.0,0.0,0.0
890,891,0,3,1,32.000000,0,0,7.7500,0.0,1.0,0.0

In [78]:
#------ Test Verisi İçin İşlemler (Aynısı) ---
embarked_test = ohe.transform(test_df[["Embarked"]]).toarray() #fit yok
embarked_test_df = pd.DataFrame(embarked_test, columns=ohe.get_feature_names_out(["Embarked"]))
embarked_test_df.index = test_df.index
test_df = test_df.drop("Embarked", axis=1)
test_df = pd.concat([test_df, embarked_test_df], axis=1)

embarked_test_df

     Embarked_C  Embarked_Q  Embarked_S
0           0.0         1.0         0.0
1           0.0         0.0         1.0
2           0.0         1.0         0.0
3           0.0         0.0         1.0
4           0.0         0.0         1.0
..          ...         ...         ...
413         0.0         0.0         1.0
414         1.0         0.0         0.0
415         0.0         0.0         1.0
416         0.0         0.0         1.0
417         1.0         0.0         0.0

[418 rows x 3 columns]

In [79]:
test_df

,PassengerId,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked_C,Embarked_Q,Embarked_S
0,892,3,1,34.500000,0,0,7.8292,0.0,1.0,0.0
1,893,3,0,47.000000,1,0,7.0000,0.0,0.0,1.0
2,894,2,1,62.000000,0,0,9.6875,0.0,1.0,0.0
3,895,3,1,27.000000,0,0,8.6625,0.0,0.0,1.0
4,896,3,0,22.000000,1,1,12.2875,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...
413,1305,3,1,29.699118,0,0,8.0500,0.0,0.0,1.0
414,1306,1,0,39.000000,0,0,108.9000,1.0,0.0,0.0
415,1307,3,1,38.500000,0,0,7.2500,0.0,0.0,1.0
416,1308,3,1,29.699118,0,0,8.0500,0.0,0.0,1.0
417,1309,3,1,29.699118,1,1,22.3583,1.0,0.0,0.0

In [ ]:
y = train_df["Survived"]
X = train_df.drop(["Survived", "PassengerId"], axis=1)

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=0)

from sklearn.preprocessing import StandardScaler #verilerin ölçeklenmesi yani genelde -3 ile 3 arası stanadart spamsı 1 olan değerler üretmek için
sc = StandardScaler()

X_train = sc.fit_transform(x_train)
X_test = sc.transform(x_test)

from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train,y_train) #X_trainden y_traini öğren

y_pred = regressor.predict(X_test) # x in test olarak ayrılmış kısmını (X_test) tahmin eder
y_pred
X

c:\Users\OĞUZ\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked_C,Embarked_Q,Embarked_S
0,3,1,22.000000,1,0,7.2500,0.0,0.0,1.0
1,1,0,38.000000,1,0,71.2833,1.0,0.0,0.0
2,3,0,26.000000,0,0,7.9250,0.0,0.0,1.0
3,1,0,35.000000,1,0,53.1000,0.0,0.0,1.0
4,3,1,35.000000,0,0,8.0500,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...
886,2,1,27.000000,0,0,13.0000,0.0,0.0,1.0
887,1,0,19.000000,0,0,30.0000,0.0,0.0,1.0
888,3,0,29.699118,1,2,23.4500,0.0,0.0,1.0
889,1,1,26.000000,0,0,30.0000,1.0,0.0,0.0
890,3,1,32.000000,0,0,7.7500,0.0,1.0,0.0

In [81]:
y_test

495    0
648    0
278    0
31     1
255    1
      ..
17     1
476    0
533    1
416    1
345    1
Name: Survived, Length: 295, dtype: int64

In [82]:
import statsmodels.api as sm
X_list = np.append(arr=np.ones((len(X), 1)).astype(int), values=X, axis=1) 
X_l = X_list[:, [0, 1, 2, 3, 4, 5, 6, 7, 8]]
X_l = np.array(X_l, dtype=float)
model = sm.OLS(y, X_l).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:               Survived   R-squared:                       0.398
Model:                            OLS   Adj. R-squared:                  0.393
Method:                 Least Squares   F-statistic:                     72.95
Date:                Tue, 23 Dec 2025   Prob (F-statistic):           5.10e-92
Time:                        19:21:57   Log-Likelihood:                -395.73
No. Observations:                 891   AIC:                             809.5
Df Residuals:                     882   BIC:                             852.6
Df Model:                           8
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          1.2831      0.071     18.041      0.000       1.143       1.423
x1            -0.1722      0.020     -8.519      0.000      -0.212      -0.132
x2            -0.5050      0.028    -17.906      0.000      -0.560      -0.450
x3            -0.0059      0.001     -5.443      0.000      -0.008      -0.004
x4            -0.0413      0.013     -3.165      0.002      -0.067      -0.016
x5            -0.0162      0.018     -0.888      0.375      -0.052       0.020
x6             0.0003      0.000      0.887      0.376      -0.000       0.001
x7             0.0643      0.034      1.870      0.062      -0.003       0.132
x8             0.0634      0.047      1.337      0.181      -0.030       0.156
==============================================================================
Omnibus:                       38.761   Durbin-Watson:                   1.931
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               42.837
Skew:                           0.534   Prob(JB):                     4.99e-10
Kurtosis:                       3.124   Cond. No.                         360.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [83]:
X_l = X_list[:,[0,1,2,3,4,5,7,8]]
X_l = np.array(X_l, dtype=float)
model = sm.OLS(y, X_l).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:               Survived   R-squared:                       0.398
Model:                            OLS   Adj. R-squared:                  0.393
Method:                 Least Squares   F-statistic:                     83.28
Date:                Tue, 23 Dec 2025   Prob (F-statistic):           7.94e-93
Time:                        19:21:57   Log-Likelihood:                -396.13
No. Observations:                 891   AIC:                             808.3
Df Residuals:                     883   BIC:                             846.6
Df Model:                           7
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          1.3124      0.063     20.854      0.000       1.189       1.436
x1            -0.1815      0.017    -10.525      0.000      -0.215      -0.148
x2            -0.5061      0.028    -17.969      0.000      -0.561      -0.451
x3            -0.0059      0.001     -5.476      0.000      -0.008      -0.004
x4            -0.0395      0.013     -3.064      0.002      -0.065      -0.014
x5            -0.0133      0.018     -0.743      0.458      -0.048       0.022
x6             0.0699      0.034      2.068      0.039       0.004       0.136
x7             0.0653      0.047      1.380      0.168      -0.028       0.158
==============================================================================
Omnibus:                       38.148   Durbin-Watson:                   1.931
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               42.070
Skew:                           0.529   Prob(JB):                     7.32e-10
Kurtosis:                       3.126   Cond. No.                         168.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [84]:
X_l = X_list[:, [0, 1, 2, 3, 4, 7, 8]]
X_l = np.array(X_l, dtype=float)
model = sm.OLS(y, X_l).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:               Survived   R-squared:                       0.397
Model:                            OLS   Adj. R-squared:                  0.393
Method:                 Least Squares   F-statistic:                     97.11
Date:                Tue, 23 Dec 2025   Prob (F-statistic):           1.01e-93
Time:                        19:21:57   Log-Likelihood:                -396.41
No. Observations:                 891   AIC:                             806.8
Df Residuals:                     884   BIC:                             840.4
Df Model:                           6
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          1.3042      0.062     21.055      0.000       1.183       1.426
x1            -0.1816      0.017    -10.532      0.000      -0.215      -0.148
x2            -0.5015      0.027    -18.259      0.000      -0.555      -0.448
x3            -0.0058      0.001     -5.436      0.000      -0.008      -0.004
x4            -0.0431      0.012     -3.609      0.000      -0.067      -0.020
x5             0.0703      0.034      2.081      0.038       0.004       0.137
x6             0.0688      0.047      1.462      0.144      -0.024       0.161
==============================================================================
Omnibus:                       37.327   Durbin-Watson:                   1.932
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               41.054
Skew:                           0.522   Prob(JB):                     1.22e-09
Kurtosis:                       3.127   Cond. No.                         166.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [85]:
X_l = X_list[:, [0, 1, 2, 3, 4, 7]]
X_l = np.array(X_l, dtype=float)
model = sm.OLS(y, X_l).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:               Survived   R-squared:                       0.396
Model:                            OLS   Adj. R-squared:                  0.392
Method:                 Least Squares   F-statistic:                     116.0
Date:                Tue, 23 Dec 2025   Prob (F-statistic):           2.58e-94
Time:                        19:21:57   Log-Likelihood:                -397.48
No. Observations:                 891   AIC:                             807.0
Df Residuals:                     885   BIC:                             835.7
Df Model:                           5
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          1.2992      0.062     20.993      0.000       1.178       1.421
x1            -0.1761      0.017    -10.460      0.000      -0.209      -0.143
x2            -0.5066      0.027    -18.583      0.000      -0.560      -0.453
x3            -0.0057      0.001     -5.350      0.000      -0.008      -0.004
x4            -0.0440      0.012     -3.687      0.000      -0.067      -0.021
x5             0.0651      0.034      1.936      0.053      -0.001       0.131
==============================================================================
Omnibus:                       36.370   Durbin-Watson:                   1.926
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               39.928
Skew:                           0.516   Prob(JB):                     2.14e-09
Kurtosis:                       3.104   Cond. No.                         165.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [86]:
X_l = X_list[:, [0, 1, 2, 3, 4]]
X_l = np.array(X_l, dtype=float)
model = sm.OLS(y, X_l).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:               Survived   R-squared:                       0.393
Model:                            OLS   Adj. R-squared:                  0.391
Method:                 Least Squares   F-statistic:                     143.6
Date:                Tue, 23 Dec 2025   Prob (F-statistic):           1.30e-94
Time:                        19:21:57   Log-Likelihood:                -399.36
No. Observations:                 891   AIC:                             808.7
Df Residuals:                     886   BIC:                             832.7
Df Model:                           4
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          1.3352      0.059     22.585      0.000       1.219       1.451
x1            -0.1837      0.016    -11.214      0.000      -0.216      -0.152
x2            -0.5094      0.027    -18.680      0.000      -0.563      -0.456
x3            -0.0058      0.001     -5.462      0.000      -0.008      -0.004
x4            -0.0454      0.012     -3.801      0.000      -0.069      -0.022
==============================================================================
Omnibus:                       36.819   Durbin-Watson:                   1.921
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               40.455
Skew:                           0.519   Prob(JB):                     1.64e-09
Kurtosis:                       3.115   Cond. No.                         155.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [87]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

# Orijinal X verisinden sadece bu sütunları alıyoruz.
X_opt = X.iloc[:, [0, 1, 2, 3]].values 

# Optimize edilmiş veriyi tekrar eğitim ve test olarak ayırıyoruz.
X_train, X_test, y_train, y_test = train_test_split(X_opt, y, test_size=0.33, random_state=0)

regressor_final = LinearRegression()
regressor_final.fit(X_train, y_train)

y_pred_final = regressor_final.predict(X_test)

print("Final Tahminleri Oluşturuldu.")

y_pred_final[:10]

Final Tahminleri Oluşturuldu.

array([0.11233677, 0.11233677, 0.05197153, 0.92858284, 0.62972334,
       0.46440291, 0.91601046, 0.96982967, 0.44347723, 0.62554268])

In [89]:
from sklearn.metrics import accuracy_score

# Tahminleri 0 veya 1'e yuvarlıyoruz 
y_pred_rounded = [round(value) for value in y_pred_final]

# Doğruluk oranını hesaplıyoruz
dogruluk = accuracy_score(y_test, y_pred_rounded)

print(f"Modelin Doğruluk Oranı : %{dogruluk * 100}")

Modelin Doğruluk Oranı : %78.98305084745762